apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: monitoring-agent
  labels:
    app: monitoring-agent
spec:
  template:
    metadata:
      labels:
        name: monitoring-agent
    spec:
      containers:
        - name: node-app
          image: chanakyacool/demo-node-app
          ports:
            - name: node-app-port
              containerPort: 3000