apiVersion: v1
kind: Service
metadata:
  name: wp-service
spec:
  selector:
    app: wp-demo-app
  ports:
  - port: 31001
    nodePort: 31001
    targetPort: http-port
    protocol: TCP
  type: NodePort
