apiVersion: v1
kind: Pod
metadata:
  name: node-app.example.com
  labels:
    name: node-app
spec:
  containers:
  - name: demo-node-app
    image: chanakyacool/demo-node-app:v2
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 3000
  nodeSelector:
    hardware: low-spec
