apiVersion: v1
kind: Pod
metadata:
  name: node-app
  labels:
    name: node-app
spec:
  volumes:
    - name: credvolume
      secret:
        secretName: node-app-secret
  containers:
  - name: node-app
    image: chanakyacool/demo-node-app:v2
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 3000
    livenessProbe:
      httpGet:
        path: /
        port: 3000
      initialDelaySeconds: 15
      timeoutSeconds: 30
    # env:
    #   - name: SECRET_USERNAME
    #     valueFrom:
    #       secretKeyRef:
    #         name: node-app-secret
    #         key: username
    #   - name: SECRET_PASSWORD
    #     valueFrom:
    #       secretKeyRef:
    #         name: node-app-secret
    #         key: password
    volumeMounts:
      - mountPath: /etc/creds # /etc/creds/node-app-secret/username, password
        name: credvolume
        readOnly: true