apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      volumes:
        - name: node-app-secret-volume
          secret:
            secretName: node-secret
      containers:
      - name: demo-node-app
        image: chanakyacool/demo-node-app:v2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
        volumeMounts:
          - mountPath: /etc/creds
            name: node-app-secret-volume
            readOnly: true
