apiVersion: v1
kind: Pod
metadata:
  name: node-app-pod
  labels:
    app: node-app-pod
spec:
  containers:
  - name: node-app
    image: chanakyacool/demo-node-app
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - name: node-app-port
      containerPort: 3000
