apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  # minReadySeconds: 10
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue
spec:
  # minReadySeconds: 10
  replicas: 1
  selector:
    matchLabels:
      app: queue
  template:
    metadata:
      labels:
        app: queue
    spec:
      containers:
      - name: webapp-queue
        image: richardchesterwood/k8s-fleetman-queue:release1