apiVersion: v1
kind: Service
metadata:
  name: fleetman-service # uniq
spec:
  selector:
    app: webapp
  ports:
  - name: http
    port: 80
    nodePort: 30080 # should be > 30000
  type: NodePort # can be exposed to the outsideworld
  # ClusterIP # use only when it should be accesible inside the cluster not external traffic (browser) like micro service

---

apiVersion: v1
kind: Service
metadata:
  name: queue-service
spec:
  selector:
    app: queue
  ports:
  - name: http
    port: 8161
    nodePort: 30010
  type: NodePort